# Generated by Django 5.2.8 on 2025-11-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "amount_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите сумму платежа",
                        max_digits=10,
                        verbose_name="Сумма платежа",
                    ),
                ),
                (
                    "date_pay",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату платежа",
                        verbose_name="Дата платежа",
                    ),
                ),
                (
                    "method_payment",
                    models.CharField(
                        choices=[
                            ("Наличные", "Наличные"),
                            ("Безналичные", "Безналичные"),
                        ],
                        default="Наличные",
                        help_text="Укажите способ оплаты",
                        max_length=100,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "paid_course_or_lesson",
                    models.ForeignKey(
                        help_text="Укажите курс или урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Оплата курса или урока",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["date_pay", "method_payment", "paid_course_or_lesson"],
            },
        ),
    ]
