# Generated by Django 5.2.8 on 2025-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Укажите статус активности",
                verbose_name="Поле активности",
            ),
        ),
    ]
