# Generated by Django 5.2.8 on 2025-12-07 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_groups_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Укажите сумму", verbose_name="Сумма"
                    ),
                ),
                (
                    "link_payment",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату",
                        max_length=450,
                        null=True,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Укажите ID сесссии",
                        max_length=255,
                        null=True,
                        verbose_name="ID сесссии",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка для платежа",
                "verbose_name_plural": "Ссылки для платежей",
            },
        ),
    ]
