# Generated by Django 5.2.8 on 2025-11-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmodel",
            name="course",
            field=models.ForeignKey(
                help_text="Добавьте к какому курсу относится урок",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="materials.coursemodel",
                verbose_name="Урок из курса",
            ),
        ),
        migrations.AlterField(
            model_name="lessonmodel",
            name="video_link",
            field=models.URLField(
                blank=True,
                help_text="Добавьте ссылку на видео",
                max_length=500,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
