# Generated by Django 5.2.8 on 2025-11-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lessonmodel_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmodel",
            name="course",
            field=models.ForeignKey(
                help_text="Добавьте к какому курсу относится урок",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.coursemodel",
                verbose_name="Урок из курса",
            ),
        ),
    ]
